config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/projects/most_tasks' => 'projects#most_tasks'
  get '/projects/upcoming_dates' => 'projects#upcoming_dates'
  get '/tasks/upcoming_dates' => 'tasks#upcoming_dates'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  get '/logout' => 'sessions#destroy'

  #omniauth callback route
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :projects do
    resources :tasks
  end

  resources :tasks

  resources :users do
    resources :projects, shallow: true
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

    belongs_to :user
    has_many :tasks, dependent: :destroy 
    has_many :users, through: :tasks

    validates :title, presence: true 
    validates :description, presence: true 
    validates :due_date, presence: true 

    scope :most_recent, -> { order("created_at desc") }
    scope :most_tasks, -> { left_joins(:tasks).group('projects.id').order('count(tasks.project_id) desc') }
    scope :upcoming_dates, -> { order('projects.due_date') }

end

app/models/task.rb
class Task < ApplicationRecord
    
    belongs_to :user 
    belongs_to :project

    validates :name, presence: true 
    validates :description, presence: true
    validates :due_by, presence: true 

    scope :recently_created, -> { order('tasks.created_at desc') }
    scope :upcoming_dates, -> { order('tasks.due_by') }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :projects
    has_many :tasks

    validates :name, presence: true 
    validates :email, presence: true
    validates :password, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #gives access to methods in the views
    helper_method :current_user, :logged_in?, :pretty_date


    private
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

    def pretty_date(date)
        date.strftime(" %B %d, %Y ")
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_project, only: [:edit, :update, :show, :destroy]
    before_action :redirect_if_not_project_creator, only: [:edit, :update]

    def new
      if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @project = @user.projects.build
      else
        @project = Project.new
      end
    end
  
    def index
      @projects = Project.most_recent
    end
  
    def create
      @project = Project.new(project_params)
      @project.user_id = current_user.id
      if @project.save
        redirect_to projects_path
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      redirect_to projects_path if !@project || @project.user != current_user
      if @project.update(project_params)
        redirect_to project_path(@project)
      else
        render :edit
      end
    end
  
    def show
    end

    def destroy
      @project.destroy
      redirect_to projects_path
    end

    def most_tasks
      @projects = Project.most_tasks
    end

    def upcoming_dates
      @projects = Project.upcoming_dates
    end
  
    private
  
    def project_params
      params.require(:project).permit(:title, :description, :due_date)
    end

    def set_project
      @project = Project.find_by_id(params[:id])
      if !@project
        flash[:message] = "Project was not found"
        redirect_to projects_path
      end
    end 

    def redirect_if_not_project_creator
      redirect_to projects_path if @project.user != current_user
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    def home 
      @user = current_user
    end

    def create 
      user = User.find_by(name: params[:user][:name])
      if user && user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:message] = "Incorrect login information, please try again."
        redirect_to "/login"
      end
    end 

    def destroy
      session.clear
      redirect_to root_path
    end


    def google
      #find_or_create a user using the attributes auth
      @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
        user.name = auth["info"]["name"]
        user.password = SecureRandom.hex(10)
      end
      if @user.save | !!@user
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        redirect_to '/'
      end
    end

    private 

    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_task_creator, only: [:edit, :update]

    def index
      if params[:project_id] && @project = Project.find_by_id(params[:project_id])

          if params[:search]
            @tasks = Task.where(name: params[:search], project_id: @project.id)
            render :index
          else
            @tasks = @project.tasks.recently_created
          end

      else

          @error = "That project doesn't exist" if params[:project_id]
          if params[:search]
            @tasks = Task.where("name like ?", "%#{params[:search]}%")
            
            render :index
          else
            @tasks = Task.recently_created
          end

      end
    end
 
    def new
      if params[:project_id] && @project = Project.find_by_id(params[:project_id])
        @task = @project.tasks.build
      else
        @error = "That project doesn't exist" if params[:project_id]
        @task = Task.new
      end
    end
 
    def create
      @task = current_user.tasks.build(task_params)
      if @task.save
        redirect_to projects_path
      else
        render :new
      end
    end
 
    def show
    end

    def edit
    end
 
    def update
      if @task.update(task_params)
        redirect_to project_path
      else
        render :edit
      end
    end

    def destroy
      @task.destroy
      redirect_to tasks_path
    end

    def upcoming_dates
      @tasks = Task.upcoming_dates
    end
 
    private

    def task_params
      params.require(:task).permit(:name, :description, :due_by, :project_id, :search)
    end

    def set_task
      @task = Task.find_by(id: params[:id])
      if !@task
        flash[:message] = "Task was not found"
        redirect_to tasks_path
      end
    end

    def redirect_if_not_task_creator
      redirect_to tasks_path if @task.user != current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            #redirect to the show page
            redirect_to @user
        else
            render :new
        end
    end

    def show 
        redirect_if_not_logged_in
        redirect_to '/' if !@user
    end

    private 

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

    def index_display_header
      if @user
        content_tag(:h1, "#{@user.name}'s Projects:")
      else
        content_tag(:h2, "All Projects")
      end
    end
  
    def display_projects
      if @user.projects.empty?
        tag.h2("No Projects Yet")
      else
        user = @user == current_user ? 'Your' : "#{@user.name}'s"
        content_tag(:h2, "#{user} #{pluralize(@user.projects.count, 'Project')}:")
      end
    end

end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>

  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <% object.errors.full_messages.each_with_index do |msg, index| %>
      <%= "#{index + 1}. #{msg}" %>
      <br><br>
    <% end %>
  </div>

<% end %>

app/views/layouts/application.html.erb
  
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        background: gray;
      }

      a {
        text-decoration: none;
      }

      a:active {
        background: black;
        color: white;
      }

      a:link {
        background: black;
        color: white;
      }

      a:visited {
        background: black;
        color: white;
      }

      a:hover {
        font-size: 20px;
        font-weight: bold;
      }

      .card-container {
        border-radius: 15px;
        background: white;
      }

      .card {
        margin-top: 10px;
        padding: 10px;
      }

      .card h4 {
        margin-left: 10px;
      }

      .card h2 {
        border-bottom: solid 1px black;
      }

      h1 {
        color: white;
        padding: 3px;
        border-bottom: 3px solid black;
      }

      #username {
        margin-top: 0;
      }

      #username a {
        color: black;
        background: white;
      }

      .sidenav {
        height: 100%;
        width: 160px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
      }

      .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
      }

      .sidenav a:hover {
        color: #f1f1f1;
        border-left: solid 1px white;
      }

      form {
        padding: 10px;
      }

      .main {
        margin-left: 160px;
        padding: 10px;
      }
    </style>
    <title>Task Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>

    <div class="sidenav">
      <% if logged_in?%>
        <h3 id="username"><%= link_to current_user.name, user_path(current_user)%></h3>
        <%= link_to "All Projects", projects_path %>
        <%= link_to "Add Project", new_project_path %>
        <%= link_to "All Tasks", tasks_path %>
        <%= link_to "Add a Task", new_task_path %>
        <br />
        <%= link_to "Home", user_path(current_user)%>
        <%= link_to "Logout", logout_path, method:"delete"%>

      <% else %>
        <a><%=link_to "Sign Up", signup_path %></a> |
        <a><%=link_to "Log In", login_path %></a> |
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f|%>

  <%= f.label :title, "Project Title" %><br>
  <%= f.text_field :title %>
  <br><br>
  <%= f.label :description, "Description of the Project" %><br>
  <%= f.text_area :description %>
  <br><br>
  <%= f.label :due_date, "When is the Project Due?" %><br>
  <%= f.date_field :due_date %>
  <br><br>
  <%= f.submit %>

<% end %>

app/views/projects/_projects.html.erb
<div class="card-container">

    <% if projects.empty? %>

        <h2>No projects yet. Create a project <%= link_to "here", new_project_path%></h2>

    <% else %> 

        <% projects.each do |p|%> 

            <div class="card">

                <h2><%=p.title%></h2>

                <h4><u>Goal:</u> <%= p.description %></h4> 

                <h4><u>Due:</u> <%= pretty_date(p.due_date)%></h4> 

                <h4><u>Tasks:</u> <%= p.tasks.size %></h4>

                <%=link_to "Click here to view the project", project_path(p)%>

            </div>

        <% end %>

    <% end %>

</div>

app/views/projects/edit.html.erb
<div class="main">

    <h1>Edit <%= @project.title%></h1>

    <%= render partial: "layouts/errors", locals: {object: @project} %>

    <%= render partial: "form", locals: {project: @project}%>

    <%= button_to "Delete", project_path(@project), method: :delete %>

</div>

app/views/projects/index.html.erb
<div class="main">

    <h1>Projects</h1>

    <%= link_to "Most Tasks", projects_most_tasks_path %> |
    <%= link_to "Projects Due soon", projects_upcoming_dates_path %>

    <%= render partial: "projects", locals: {projects: @projects} %>

<div>

app/views/projects/most_tasks.html.erb
<div class="main">
    <h1>Project with the most tasks: ( Highest to Lowest )</h1>

    <%= link_to "Projects Due soon", projects_upcoming_dates_path %>

    <%= render partial: "projects", locals: {projects: @projects} %>
</div>

app/views/projects/new.html.erb
<div class="main">
    <h1>New Project</h1>


    <%= render partial: "layouts/errors", locals: {object: @project} %>
    <!-- render the errors partial, send it the @post as the 'object' -->

    <%= render partial: "form", locals: {project: @project}%>   
</div>

app/views/projects/show.html.erb
<div class="main">
    <h1><%=@project.title%></h1>

    <h4>Project Created By: <%=@project.user.name%> </h4>

    <div>
        <strong>Project Description:</strong><br>
        <%=@project.description%>
    </div>

    <br>

    <div>
        <strong>Project Due Date:</strong><br>
        <%=pretty_date(@project.due_date)%>
    </div>

    <% if @project.user == current_user %>
        <h4><%= link_to "Edit Project", edit_project_path(@project)%></h4>
    <% end %>

    <p><%= link_to 'Add a new task', new_project_task_path(@project) %></p>

    <p><%= link_to 'See all tasks', project_tasks_path(@project) if !@project.tasks.empty? %></p>
</div>

app/views/projects/upcoming_dates.html.erb
<div class="main">
    <h1>Upcoming Project dates</h1>

    <%= link_to "Most Tasks", projects_most_tasks_path %>

    <%= render partial: "projects", locals: {projects: @projects} %>

</div>

app/views/tasks/_search_form.html.erb
<%= form_tag url_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Submit", name: nil %>
<% end %>
<br>

app/views/tasks/_tasks.html.erb
<div class="card-container">

  <% tasks.each do |t|%>

    <div class="card">

      <h2><u>Task:</u> <%= t.name %></h2> 

      <h4><u>Goal:</u> <%= t.description %></h4> 

      <h4><u>Due:</u> <%= pretty_date(t.due_by)%></h4> 

      <h4>Project: <strong><%= link_to t.project.title, project_path(t.project_id) %></strong> </h4>

      <% if t.user == current_user %>
      <%= link_to "Edit Task", edit_task_path(t)%>
      <% end %>
    
    </div>
    
  <% end %>

</div>
  

app/views/tasks/edit.html.erb
<div class="main">
  <h1>Edit Task: <%= @task.name%></h1>

  <%= render partial: "layouts/errors", locals: {object: @task} %>

  <%= form_for(@task) do |f|%>

    <%= f.label :project, "Project Name"%>
    <%= f.collection_select :project_id, Project.all, :id, :title %>
    <br><br>
    <%= f.label :name, "Task Name" %><br>
    <%= f.text_field :name %>
    <br><br>
    <%= f.label :description, "Description of the Task" %><br>
    <%= f.text_area :description %>
    <br><br>
    <%= f.label :due_by, "When is the task due?" %><br>
    <%= f.date_field :due_by %>
    <br><br>
    <%= f.submit "Edit Task" %>

  <% end %>

  <%= button_to "Delete",
    task_path(@task),
    method: :delete
  %>
</div>

app/views/tasks/index.html.erb
<div class="main">
    <% if @project %>

        <h1>Tasks for - <%=@project.title%></h1>

        <%= render partial: "search_form", locals: { url_path: project_tasks_path(@project) } %>

    <% else %>

        <h1>All Tasks</h1>

        <%= render partial: "search_form", locals: { url_path: tasks_path } %>

    <% end %>

    <%= link_to 'Tasks Due Soon', tasks_upcoming_dates_path %>

    <%= render partial: "tasks", locals: { tasks: @tasks } %>

</div>

app/views/tasks/new.html.erb
<div class="main">
    <% if @task.project %>
        <h1>New Task for - <%= @task.project.title%></h1>
    <% else %>
        <h1>New Task</h1>
    <% end %>



    <%= render partial: "layouts/errors", locals: {object: @task} %>

    <%= form_for([@task.project,@task]) do |f|%>

        <% if !@task.project %>
            <%= f.label :project %>
            <%= f.collection_select :project_id, Project.all, :id, :title %>
        <% else %>
            <%= f.hidden_field :project_id %>
            Project Due Date: <%= pretty_date(@task.project.due_date)%>
        <% end %>
            <br><br>
            <%= f.label :name, "Name of task" %><br>
            <%= f.text_field :name %>
            <br><br>
            <%= f.label :description, "Description of the Task " %><br>
            <%= f.text_area :description %>
            <br><br>
            <%= f.label :due_by, "When is the Task Due?" %><br>
            <%= f.date_field :due_by %>
            <br><br>
            <%= f.submit "Create Task"%>

    <% end %>
</div>

app/views/tasks/show.html.erb
<div class="main">

  <div class="card">

    <h1>Name of Task: <%= @task.name %></h1>
    <h2>Description: <br><%= @task.description%></h2>
    <h2>Due By: <%= @task.due_by.strftime("%m/%d/%Y")%> </h2> 
    <h3>Task Creator: <br><%= @task.user.name%></h3>

    <% if @task.user == current_user %>
      <%= link_to "Edit Task", edit_task_path(@task)%>
    <% end %>

    <h4>See the full Project Here: <%= link_to @task.project.title, project_path(@task.project_id) %></h4>

  </div>
  
</div>

app/views/tasks/upcoming_dates.html.erb
<div class="main">
    <h1>Upcoming Task Dates</h1>

    <%= render partial: 'tasks', locals: {tasks: @tasks}%>
</div>

app/views/users/new.html.erb
<div class="main">
  <h1>Sign Up</h1>

  <%= render partial: "layouts/errors", locals: {object: @user} %>


  <%= form_for(@user, url:'/signup') do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, required:true%>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>

    <%= f.submit "Create Account" %>

  <% end %>
</div>